import os
import sys
from graph import app_graph

if __name__ == "__main__":
    print("\n=== FinTech Agent Engine: Strategy Generator & Coder ===")
    
    input_file_path = "/app/user_query.md"
    
    if not os.path.exists(input_file_path):
        print(f"[ERROR] Input file not found at {input_file_path}")
        sys.exit(1)
        
    with open(input_file_path, "r", encoding="utf-8") as f:
        user_input = f.read().strip()
        
    if not user_input:
        print(f"[ERROR] {input_file_path} is empty. Please add a prompt and try again.")
        sys.exit(1)

    print(f"\n[SYSTEM] Read query from file: '{user_input[:50]}...'")
    print("[SYSTEM] Sending request to the Multi-Agent Graph. Please wait...")
    
    initial_state = {
        "user_query": user_input,
        "current_concept": "",
        "simulation_results": "",
        "market_context": "",
        "critique_feedback": "",
        "revision_count": 0,
        "approved": False,
        "backtest_code": ""
    }

    # Execute the LangGraph workflow
    final_state = app_graph.invoke(initial_state)
    concept = final_state["current_concept"]
    code = final_state.get("backtest_code", "")
    
    print("\n================ FINAL STRATEGY CONCEPT ================\n")
    print(concept)
    print("\n========================================================")

    # --- OUTPUT SAVING LOGIC ---
    output_dir = "/app/outputs"
    os.makedirs(output_dir, exist_ok=True) 
    
    # 1. Save the Strategy Markdown
    md_file_path = os.path.join(output_dir, "latest_strategy.md")
    with open(md_file_path, "w", encoding="utf-8") as f:
        f.write("# Autonomous Trading Strategy Concept\n\n")
        f.write(f"**Generated by:** Phi-3 via LangGraph\n\n")
        f.write(f"**Original Query:** *{initial_state['user_query']}*\n\n")
        f.write("---\n\n")
        f.write(concept)
        
    print(f"\n[SUCCESS] Strategy safely saved to {md_file_path}")

    # 2. Save the Backtest Python Code (If it was generated)
    if code:
        py_file_path = os.path.join(output_dir, "backtest.py")
        with open(py_file_path, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"[SUCCESS] Python backtest code safely saved to {py_file_path}")
    else:
        print("\n[WARNING] No code was generated. The strategy may have been rejected by the Validator or hit the max loop limit.")

    # 3. Print the execution results
    execution_error = final_state.get("execution_error", "")
    simulation_results = final_state.get("simulation_results", "")
    
    print("\n================ BACKTEST RESULTS ================\n")
    if simulation_results:
        print(simulation_results)
    elif execution_error:
        print("[FAILED TO EXECUTE] The AI could not fix the code after 5 attempts.")
        print(f"Final Error:\n{execution_error}")
    else:
        print("No simulation was run.")
    print("\n==================================================")