import os
from graph import app_graph

if __name__ == "__main__":
    print("Sending request to the Multi-Agent Graph...\n")
    
    # Define the initial state (The user's request)
    initial_state = {
        "user_query": "Create a low-risk momentum trading strategy specifically for large-cap tech stocks like Apple and Microsoft.",
        "current_concept": "",
        "simulation_results": "",
        "market_context": "",
        "critique_feedback": "",
        "revision_count": 0,
        "approved": False
    }

    # Execute the LangGraph workflow
    final_state = app_graph.invoke(initial_state)
    concept = final_state["current_concept"]
    
    print("\n================ FINAL STRATEGY CONCEPT ================\n")
    print(concept)
    print("\n========================================================")

    # --- NEW OUTPUT LOGIC ---
    # Define an outputs folder inside our app directory
    output_dir = "/app/outputs"
    os.makedirs(output_dir, exist_ok=True) # Creates the folder if it doesn't exist
    
    # Save the output as a Markdown document
    file_path = os.path.join(output_dir, "latest_strategy.md")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write("# Autonomous Trading Strategy Concept\n\n")
        f.write(f"**Generated by:** Phi-3 via LangGraph\n\n")
        f.write(f"**Original Query:** *{initial_state['user_query']}*\n\n")
        f.write("---\n\n")
        f.write(concept)
        
    print(f"\n[SUCCESS] Strategy successfully saved to {file_path}")