from typing import TypedDict

class AgentState(TypedDict):
    """
    This defines the shared memory object that all agents will read from and write to.
    """
    # The initial input from the user (e.g., "Create a low-risk tech stock strategy")
    user_query: str
    
    # The strategy proposed by the Generator agent
    current_concept: str
    
    # The backtesting results generated by the Validator agent (Python REPL)
    simulation_results: str
    
    # The market data retrieved by the Contextualizer agent (RAG / yfinance)
    market_context: str
    
    # The feedback from the Critic agent if the strategy is rejected
    critique_feedback: str
    
    # A counter to prevent the agents from debating infinitely
    revision_count: int
    
    # The final decision from the Critic (True = Output to user, False = Route back to Generator)
    approved: bool

    # Stores the generated Python script
    backtest_code: str  

    # Stores the Python traceback
    execution_error: str 
    
    # Prevents infinite coding loops
    code_revisions: int 